name: Dart Frontend

on:
  push:
    paths:
      - frontend/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          architecture: x64
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
          flutter --version
        working-directory: ./frontend
      - run: flutter --version

      - name: Install Flutter dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Verify Flutter formatting
        working-directory: ./frontend
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze Flutter project source
        working-directory: ./frontend
        run: flutter analyze

      - name: Run Flutter tests
        working-directory: ./frontend
        run: flutter test

      - name: Run Flutter Doctor
        working-directory: ./frontend
        run: flutter doctor

      # Build APK
      # - name: Build Flutter APK
      #   working-directory: flutter_project
      #   run: flutter build apk --release


