name: Dart and Python

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      - name: Flutter action
        uses: subosito/flutter-action@v2.18.0

      # Flutter Setup
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml 

      - run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Verify Flutter formatting
        run: flutter format --set-exit-if-changed .

      - name: Analyze Flutter project source
        run: flutter analyze

      - name: Run Flutter tests
        run: flutter test

      # Python Steps
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry to use Python 3.12
        working-directory: backend # Change this to your Python project's folder
        run: poetry env use 3.12

      - name: Install Python dependencies
        working-directory: backend
        run: poetry install

      - name: Run Python linter (Pylint)
        working-directory: backend
        run: poetry run pylint .

      - name: Verify Python formatting
        working-directory: backend
        run: poetry run black --check .

      - name: Run Python tests
        working-directory: backend
        run: poetry run pytest

